#!/bin/bash
ETAPE=5

# Noms des auteurs
NOM1="BODIN"
NOM2="COLIN"
NOM3="DOUANT"
NOM4="LE_COQ"

# Nom de l'archive
ARCHIVE="${NOM1}-${NOM2}-${NOM3}-${NOM4}-SIT213-Etape${ETAPE}.tar.gz"

./cleanAll

# Création de l'archive
tar --exclude='genDeliverable' -czvf "$ARCHIVE" * 

echo "Livrable créé : $ARCHIVE"
