#!/bin/bash
# Check if the project is already compiled by looking for the AllTests.class file
if [ ! -f ./bin/AllTests.class ]; then
    echo "Error: AllTests is not compiled. Please compile the project first."
    exit 1
fi

# Include the bin directory and all libraries in the classpath, and run AllTests
# java -cp "lib/*:bin" org.junit.runner.JUnitCore tests.AllTests
java -cp "lib/*:bin" org.junit.runner.JUnitCore AllTests
